// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: .proto/FileService.proto

package busproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FileService_UpdateBootstrap_FullMethodName = "/fileService.FileService/UpdateBootstrap"
	FileService_DeleteBootstrap_FullMethodName = "/fileService.FileService/DeleteBootstrap"
	FileService_UpdateService_FullMethodName   = "/fileService.FileService/UpdateService"
	FileService_DeleteService_FullMethodName   = "/fileService.FileService/DeleteService"
	FileService_UpdateSH_FullMethodName        = "/fileService.FileService/UpdateSH"
	FileService_DeleteSH_FullMethodName        = "/fileService.FileService/DeleteSH"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServiceClient interface {
	UpdateBootstrap(ctx context.Context, in *Bootstrap, opts ...grpc.CallOption) (*FileResponse, error)
	DeleteBootstrap(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*FileResponse, error)
	UpdateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*FileResponse, error)
	DeleteService(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*FileResponse, error)
	UpdateSH(ctx context.Context, in *Script, opts ...grpc.CallOption) (*FileResponse, error)
	DeleteSH(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*FileResponse, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) UpdateBootstrap(ctx context.Context, in *Bootstrap, opts ...grpc.CallOption) (*FileResponse, error) {
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, FileService_UpdateBootstrap_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DeleteBootstrap(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*FileResponse, error) {
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, FileService_DeleteBootstrap_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) UpdateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*FileResponse, error) {
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, FileService_UpdateService_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DeleteService(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*FileResponse, error) {
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, FileService_DeleteService_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) UpdateSH(ctx context.Context, in *Script, opts ...grpc.CallOption) (*FileResponse, error) {
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, FileService_UpdateSH_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DeleteSH(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*FileResponse, error) {
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, FileService_DeleteSH_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility
type FileServiceServer interface {
	UpdateBootstrap(context.Context, *Bootstrap) (*FileResponse, error)
	DeleteBootstrap(context.Context, *ServiceInfo) (*FileResponse, error)
	UpdateService(context.Context, *Service) (*FileResponse, error)
	DeleteService(context.Context, *ServiceInfo) (*FileResponse, error)
	UpdateSH(context.Context, *Script) (*FileResponse, error)
	DeleteSH(context.Context, *ServiceInfo) (*FileResponse, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFileServiceServer struct {
}

func (UnimplementedFileServiceServer) UpdateBootstrap(context.Context, *Bootstrap) (*FileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBootstrap not implemented")
}
func (UnimplementedFileServiceServer) DeleteBootstrap(context.Context, *ServiceInfo) (*FileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBootstrap not implemented")
}
func (UnimplementedFileServiceServer) UpdateService(context.Context, *Service) (*FileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateService not implemented")
}
func (UnimplementedFileServiceServer) DeleteService(context.Context, *ServiceInfo) (*FileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteService not implemented")
}
func (UnimplementedFileServiceServer) UpdateSH(context.Context, *Script) (*FileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSH not implemented")
}
func (UnimplementedFileServiceServer) DeleteSH(context.Context, *ServiceInfo) (*FileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSH not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_UpdateBootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bootstrap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UpdateBootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_UpdateBootstrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UpdateBootstrap(ctx, req.(*Bootstrap))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DeleteBootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DeleteBootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_DeleteBootstrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DeleteBootstrap(ctx, req.(*ServiceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_UpdateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UpdateService(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_DeleteService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DeleteService(ctx, req.(*ServiceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_UpdateSH_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Script)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UpdateSH(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_UpdateSH_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UpdateSH(ctx, req.(*Script))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DeleteSH_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DeleteSH(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_DeleteSH_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DeleteSH(ctx, req.(*ServiceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fileService.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateBootstrap",
			Handler:    _FileService_UpdateBootstrap_Handler,
		},
		{
			MethodName: "DeleteBootstrap",
			Handler:    _FileService_DeleteBootstrap_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _FileService_UpdateService_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _FileService_DeleteService_Handler,
		},
		{
			MethodName: "UpdateSH",
			Handler:    _FileService_UpdateSH_Handler,
		},
		{
			MethodName: "DeleteSH",
			Handler:    _FileService_DeleteSH_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: ".proto/FileService.proto",
}
